#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "Astrix WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/astrix-keygen ./build/docs/astrix-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "Astrix WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/astrix-rpc ./build/docs/astrix-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "Astrix WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/astrix-core ./build/docs/astrix-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "Astrix WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/astrix ./build/docs/astrix.ts
else
    echo "building keygen"
    typedoc --name "Astrix WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/astrix-keygen ./build/docs/astrix-keygen.ts
    echo "building rpc"
    typedoc --name "Astrix WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/astrix-rpc ./build/docs/astrix-rpc.ts
    echo "building core"
    typedoc --name "Astrix WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/astrix-core ./build/docs/astrix-core.ts
    echo "building full"
    typedoc --name "Astrix WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/astrix ./build/docs/astrix.ts

fi